version: 2

sources:
  - name: recycler_dataset
    description: A dataset with raw data streaming from devices performing edge predictions on recyleable material
    tables:
      - name: predictions_raw
        columns:
          - name: id
            description: Unique key identifying a reading from a device
            tests:
              - not_null
          - name: device_id
            description: The unique ID associated with the device that generated the prediction
            tests:
              - not_null
          - name: pred_label
            description: The predicted value
            tests:
              - not_null
              - accepted_values:
                  values: [
                            'battery',
                            'brown-glass',
                            'cardboard',
                            'compost',
                            'green-glass',
                            'metal',
                            'paper',
                            'plastic',
                            'trash',
                            'white-glass'
                          ]
          - name: pred_accuracy
            description: Accuracy of the prediction, between 0 & 100
            tests:
              - not_null
          - name: pred_datetime
            description: The datetime in UTC on which the prediction was made on the device
            tests:
              - not_null

models:
  - name: predictions_public
    description: Prediction records generated by edge devices
    columns:
      - name: prediction_id
        description: The unique ID assigned to the prediction record
        tests:
          - not_null
      - name: device_id
        description: The unique ID associated with the device that generated the prediction
        tests:
          - not_null
      - name: prediction
        description: The predicted value
        tests:
          - not_null
          - accepted_values:
              values: [
                            'battery',
                            'brown-glass',
                            'cardboard',
                            'compost',
                            'green-glass',
                            'metal',
                            'paper',
                            'plastic',
                            'trash',
                            'white-glass'
                          ]
      - name: accuracy
        description: Accuracy of the prediction, between 0 & 100
        tests:
          - not_null
      - name: predicted_on
        description: The datetime in UTC on which the prediction was made on the device
        tests:
          - not_null